
package peer;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;
import webservice.Service;


public class Interfaz extends javax.swing.JFrame {

    
    public Interfaz() {
        initComponents();
        this.pack();
    }
    
    
    
    public static void mostrarNotificacion(String notificacio) {
        textAreaNotificaciones.append("> " + notificacio + "\n");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        textAreaNotificaciones = new javax.swing.JTextArea();
        jLabelLog = new javax.swing.JLabel();
        jPanelOperaciones = new javax.swing.JPanel();
        buttonPut = new javax.swing.JButton();
        buttonGet = new javax.swing.JButton();
        jTextFieldNombrePut = new javax.swing.JTextField();
        jTextFieldNombreGet = new javax.swing.JTextField();
        jTextFieldURL = new javax.swing.JTextField();
        jPanelSeleccionPeer = new javax.swing.JPanel();
        jLabelPeer = new javax.swing.JLabel();
        jComboBoxPeer = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Distributed Hash Table");
        setMinimumSize(new java.awt.Dimension(660, 520));

        textAreaNotificaciones.setEditable(false);
        textAreaNotificaciones.setColumns(20);
        textAreaNotificaciones.setRows(5);
        jScrollPane.setViewportView(textAreaNotificaciones);

        jLabelLog.setText("Log");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jLabelLog)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jLabelLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
        );

        jPanelOperaciones.setBackground(new java.awt.Color(153, 153, 153));
        jPanelOperaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));
        jPanelOperaciones.setMinimumSize(new java.awt.Dimension(150, 300));
        jPanelOperaciones.setPreferredSize(new java.awt.Dimension(150, 300));

        buttonPut.setText("PUT");
        buttonPut.setToolTipText("");
        buttonPut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPutActionPerformed(evt);
            }
        });

        buttonGet.setText("GET");
        buttonGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetActionPerformed(evt);
            }
        });

        jTextFieldNombrePut.setText("<nombre>");

        jTextFieldNombreGet.setText("<nombre>");

        jTextFieldURL.setText("<URL recurso>");

        javax.swing.GroupLayout jPanelOperacionesLayout = new javax.swing.GroupLayout(jPanelOperaciones);
        jPanelOperaciones.setLayout(jPanelOperacionesLayout);
        jPanelOperacionesLayout.setHorizontalGroup(
            jPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonGet, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(buttonPut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombrePut)
                    .addComponent(jTextFieldNombreGet, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldURL, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelOperacionesLayout.setVerticalGroup(
            jPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldURL)
                    .addComponent(jTextFieldNombrePut)
                    .addComponent(buttonPut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombreGet)
                    .addComponent(buttonGet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSeleccionPeer.setBackground(new java.awt.Color(153, 153, 153));
        jPanelSeleccionPeer.setBorder(javax.swing.BorderFactory.createTitledBorder("Selección peer inicial"));
        jPanelSeleccionPeer.setMinimumSize(new java.awt.Dimension(150, 300));

        jLabelPeer.setText("Peer:");

        jComboBoxPeer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Peer 1 (Ordenador 1)", "Peer 2 (Ordenador 1)", "Peer 3 (Ordenador 1)", "Peer 4 (Ordenador 2)", "Peer 5 (Ordenador 2)", "Peer 6 (Ordenador 2)", "Peer 7 (Ordenador 3)", "Peer 8 (Ordenador 3)", "Peer 9 (Ordenador 3)" }));

        javax.swing.GroupLayout jPanelSeleccionPeerLayout = new javax.swing.GroupLayout(jPanelSeleccionPeer);
        jPanelSeleccionPeer.setLayout(jPanelSeleccionPeerLayout);
        jPanelSeleccionPeerLayout.setHorizontalGroup(
            jPanelSeleccionPeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSeleccionPeerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPeer, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPeer, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelSeleccionPeerLayout.setVerticalGroup(
            jPanelSeleccionPeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionPeerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSeleccionPeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPeer)
                    .addComponent(jComboBoxPeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelSeleccionPeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSeleccionPeer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jPanelOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetActionPerformed
        int numPeerInicial = jComboBoxPeer.getSelectedIndex();
        String nombre = jTextFieldNombreGet.getText();
        
        try {
            URL url;
            EntradaTEncam entrada = new EntradaTEncam(Service.CLAVES[numPeerInicial], 
                    Service.HOSTS[numPeerInicial / 3], Service.PUERTO);
            url = new URL(entrada.getURLBase() + "Peer/get?"+ ""
                    + "id=" + URLEncoder.encode(new String(Service.CLAVES[numPeerInicial]), "UTF-8") 
                    + "&name=" + URLEncoder.encode(nombre, "UTF-8"));
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            if (conn.getResponseCode() == 200) {
                BufferedReader br = new BufferedReader(new InputStreamReader(conn.getInputStream()));
                mostrarNotificacion("GET: La localización del fichero '" + nombre +
                        "' es '" + br.readLine() + "'");
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonGetActionPerformed

    private void buttonPutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPutActionPerformed
        int numPeerInicial = jComboBoxPeer.getSelectedIndex();
        String nombre = jTextFieldNombrePut.getText();
        String valor = jTextFieldURL.getText();
        try {
            URL url;
            EntradaTEncam entrada = new EntradaTEncam(Service.CLAVES[numPeerInicial], 
                    Service.HOSTS[numPeerInicial / 3], Service.PUERTO);
            url = new URL(entrada.getURLBase() + "Peer/put?"
                    + "id=" + URLEncoder.encode(new String(Service.CLAVES[numPeerInicial]), "UTF-8") 
                    + "&name=" + URLEncoder.encode(nombre, "UTF-8")
                    + "&data=" + URLEncoder.encode(valor, "UTF-8"));
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("PUT");
            if (conn.getResponseCode() == 200) {
            }
            mostrarNotificacion("PUT: Par (" + nombre + ", " + valor + ") almacenado en la DHT");
        } catch (MalformedURLException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonPutActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGet;
    private javax.swing.JButton buttonPut;
    private javax.swing.JComboBox jComboBoxPeer;
    private javax.swing.JLabel jLabelLog;
    private javax.swing.JLabel jLabelPeer;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelOperaciones;
    private javax.swing.JPanel jPanelSeleccionPeer;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTextFieldNombreGet;
    private javax.swing.JTextField jTextFieldNombrePut;
    private javax.swing.JTextField jTextFieldURL;
    private static javax.swing.JTextArea textAreaNotificaciones;
    // End of variables declaration//GEN-END:variables
}